### PR TITLE
feat: user interface

### PR DESCRIPTION
**Pull request by levynaibei**
### What does this PR do?
Adds the interface: arguments, commands and options

### How Has This Been Tested?
by running `python cli.py` on the terminal

### Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have added necessary inline code documentation

### What is the relevant issue?
issue #1

### CODE REVIEW

**Comment by yashika51** [comment]
Hi @Levy-Naibei, thanks for the PR. Can you once review my PR addressing issue #2. I believe we need to make some changes in the PR to be compatible with that.

**Comment by levynaibei** [comment]
> Hi @Levy-Naibei, thanks for the PR. Can you once review my PR addressing issue #2. I believe we need to make some changes in the PR to be compatible with that.

@yashika51 yes am on it, trying to run it locally

**Comment by Levy-Naibei** [comment]
> > Hi @Levy-Naibei, thanks for the PR. Can you once review my PR addressing issue #2. I believe we need to make some changes in the PR to be compatible with that.
> 
> @yashika51 yes am on it, trying to run it locally

@yashika51 which command runs the app?

**Review by Acrylami — CHANGES_REQUESTED** [review]
Excellent UI, I very much like the look of it
One thing, when pip installing the requirements I get an error trying to install pkg-packages, so  have to manually install the rest of the requirements file except that to get it to run. 
image
What is pkg-resources used for here and can we omit it from the requirements file?

**Pull request merged**
