### PR TITLE
Python script for issue #2

### PR DESCRIPTION
**Pull request by yashika51**
Addresses: Issue #2 

The script is complete. `get_answer()` returns a list of 5 answers. The count is set to 5 by default, however, for more than 5 answers we can change this easily.
The answers stored in the list look good, just slight formatting needs to be done to show code examples in a proper format.

### CODE REVIEW

**Review by levynaibei — COMMENTED** [review]
Hey @yashika51, 
Which command runs the app on the terminal?

**Comment by yashika51** [comment]
@Levy-Naibei The script has yet to be integrated with @Acrylami's part. For now, we manually pass the error/question to `class ask` and `get_answers()` should bring back the answers list with 5 answers.

**Review by Acrylami — COMMENTED** [review]
This is looking good, thanks Yashika.
Could you send over privately the env file for testing please?
Also could you give an example of how I can pass an error into the ask class to test your code please?

**Comment by yashika51** [comment]
Hi @Acrylami, run the code and then run commands like this(see image) from `search_answers.py`. 
You can replace text to the error message while creating the object `a`. 
We have to integrate your PR such that the message you pass is taken by object.

image

**Comment by Acrylami** [comment]
Error when getting the answers
image

**Pull request merged**
